# yaml-language-server: $schema=https://raw.githubusercontent.com/vittee/medley/develop/packages/radio/medley-discord-schema.json

db:
  driver: mongodb
  url: mongodb://${MEDLEY_MONGO_DB_HOST}:${MEDLEY_MONGO_DB_PORT}
  database: ${MEDLEY_MONGO_DB_DATABASE}
  connectionOptions:
    auth:
      username: ${MEDLEY_MONGO_DB_USER}
      password: ${MEDLEY_MONGO_DB_PASSWORD}

stations:
  default:
    name: Today FM
    description: Various genres
    artistBacklog: false
    duplicationSimilarity: 0.5
    followCrateAfterRequestTrack: true
    intros:
      - ${MEDLEY_DROP_PATH}/Music Radio Creative - This is the Station With All Your Music in One Place 1.mp3
    requestSweepers:
      - ${MEDLEY_DROP_PATH}/your/Music Radio Creative - Playing All Your Requests.mp3
      - ${MEDLEY_DROP_PATH}/your/Music Radio Creative - Playing Your Favourite Artists.mp3
      - ${MEDLEY_DROP_PATH}/your/Music Radio Creative - Simply Made for You.mp3
    musicCollections:
      bright:
        description: Bright
        path: ${MEDLEY_MUSIC_PATH}/bright
      brokenhearted:
        description: Broken Hearted
        path: ${MEDLEY_MUSIC_PATH}/brokenhearted
      chill:
        description: Chill
        path: ${MEDLEY_MUSIC_PATH}/chill
      groovy:
        description: Groovy
        path: ${MEDLEY_MUSIC_PATH}/groovy
      hurt:
        description: Hurt
        path: ${MEDLEY_MUSIC_PATH}/hurt
      lonely:
        description: Lonely
        path: ${MEDLEY_MUSIC_PATH}/lonely
      lovesong:
        description: Love Song
        path: ${MEDLEY_MUSIC_PATH}/lovesong
      joyful:
        description: Joyful
        path: ${MEDLEY_MUSIC_PATH}/joyful
      upbeat:
        description: Upbeat
        path: ${MEDLEY_MUSIC_PATH}/upbeat
      new-released:
        description: New Released
        path: ${MEDLEY_MUSIC_PATH}/new-released
        disableLatch: true
        noFollowOnRequest: true
      thai:
        auxiliary: true
        description: Thai
        path: M:\Repository\th
      inter:
        auxiliary: true
        description: International
        path: M:\Repository\inter

    sequences:
      # Randomly select this crate to play tracks from new-released, limited by one of [1, 1, 1, 2]
      - chance: random
        collections:
          - id: new-released
        limit:
          by: one-of
          list: [1, 1, 1, 2]

      # This crate has 1/3 chance of being selected, play up to 2 tracks from bright
      - chance:
          yes: 1
          no: 2
        collections:
          - id: bright
        limit:
          by: upto
          upto: 2

      # This crate always play up to 2 tracks from joyful
      - collections:
          - id: joyful
        limit:
          by: upto
          upto: 2

       # This crate has 2/6 chance of being selected, play 1-2 tracks from upbeat
      - chance:
          yes: 2
          no: 4
        collections:
          - id: upbeat
        limit:
          by: range
          range:
            min: 1
            max: 2

      # This crate has 1/4 chance of being selected, play exactly 1 track from groovy
      - chance:
          yes: 1
          no: 3
        collections:
          - id: groovy
        limit: 1

      # This crate always play 2-3 tracks from chill
      - collections:
          - id: chill
        limit:
          by: range
          range:
            min: 2
            max: 3

      # This crate always play up to 2 tracks from lovesong
      - collections:
         - id: lovesong
        limit:
          by: upto
          upto: 2

      # A compound crate, always play a track from either `lonely` or `brokenhearted` (with weights)
      - collections:
          - id: lonely
            weight: 1
          - id: brokenhearted
            weight: 0.5
        limit:
          by: upto
          upto: 1

      # This crate always play 1-2 tracks from brokenhearted
      - collections:
          - id: brokenhearted
        limit:
          by: range
          range:
            min: 1
            max: 2

      # This crate has 1/3 chance of being selected, play 0 or 1 track from hurt
      - chance:
          yes: 1
          no: 2
        collections:
          - id: hurt
        limit:
          by: upto
          upto: 1

      # This crate always play 1-2 tracks from lonely
      - collections:
          - id: lonely
        limit:
          by: range
          range:
            min: 1
            max: 2

      # This crate always play upto 2 tracks from lovesong
      - collections:
          - id: lovesong
        limit:
          by: upto
          upto: 2

      # This crate has 1/2 chance of being selected, play upto 2 tracks from chill
      - chance:
          yes: 1
          no: 1
        collections:
          - id: chill
        limit:
          by: upto
          upto: 2

    sweeperRules:
      - to:
          - lonely
          - brokenhearted
          - hurt
        path: ${MEDLEY_DROP_PATH}/to_blue

      - from:
          - lonely
          - brokenhearted
          - hurt
        to:
          - lovesong
          - chill
        path: ${MEDLEY_DROP_PATH}/blue_to_easy

      - from:
          - lonely
          - brokenhearted
          - hurt
        to:
          - upbeat
          - groovy
          - joyful
        path: ${MEDLEY_DROP_PATH}/blue_to_up

      - to:
          - upbeat
          - groovy
          - joyful
        path: ${MEDLEY_DROP_PATH}/to_up

      - from:
          - upbeat
          - groovy
          - joyful
          - bright
        path: ${MEDLEY_DROP_PATH}/from_up

      - to:
          - new-released
        path: ${MEDLEY_DROP_PATH}/fresh

automatons:
  medley:
    botToken: "${MEDLEY_DISCORD_BOT_TOKEN}"
    clientId: "${MEDLEY_DISCORD_CLIENT_ID}"
