version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 18081:8081
    depends_on:
      - mongo
  radio:
    image: nexus.coke.fyi/medley/radio:latest
    build:
      dockerfile: docker/Dockerfile
      context: ../
    # restart: always
    environment:
      MEDLEY_MUSIC_PATH: /data/musics
      MEDLEY_DROP_PATH: /data/medley-drops
      MEDLEY_MONGO_DB_HOST: mongo
      MEDLEY_MONGO_DB_PORT: 27017
      MEDLEY_MONGO_DB_USER: root
      MEDLEY_MONGO_DB_PASSWORD: example
      MEDLEY_MONGO_DB_DATABASE: medley
      MEDLEY_DISCORD_BOT_TOKEN: discord-bot-token
      MEDLEY_DISCORD_CLIENT_ID: discord-client-id
      MEDLEY_DISCORD_BASE_COMMAND: medley
    volumes:
      - /Music-Station/musics:/data/musics
      - /Music-Station/medley-drops:/data/medley-drops
    depends_on:
      - mongo
