version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  radio:
    image: medley/radio
    build:
      dockerfile: docker/Dockerfile
      context: ../
    # restart: always
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_PORT: 27017
      MONGO_DB_USER: root
      MONGO_DB_PASSWORD: example
      MONGO_DB_DATABASE: medley
      MUSIC_PATH: /musics
      SKIP_CHECK_AUDIO_DEVICE: true
    volumes:
      - "/Users/coke/Library/CloudStorage/GoogleDrive-visualizeq@gmail.com/My Drive/musics:/musics"
    depends_on:
      - mongo
