version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  radio:
    image: medley/radio
    build:
      dockerfile: docker/Dockerfile
      context: ../
    # restart: always
    env_file: .env
    volumes:
      - "/Users/coke/Library/CloudStorage/GoogleDrive-visualizeq@gmail.com/My Drive/musics:/musics"
    depends_on:
      - mongo
