version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  radio:
    image: nexus.coke.fyi/medley/radio:latest
    build:
      dockerfile: docker/Dockerfile
      context: ../
    # restart: always
    environment:
      MUSIC_PATH: /musics
      DROP_PATH: /drops
      MONGO_DB_HOST: mongo
      MONGO_DB_PORT: 27017
      MONGO_DB_USER: root
      MONGO_DB_PASSWORD: example
      MONGO_DB_DATABASE: medley
      DISCORD_BOT_TOKEN:
      DISCORD_CLIENT_ID:
      DISCORD_BASE_COMMAND: medley
    volumes:
      - "./data/musics:/musics"
      - "./data/drops:/drops"
    depends_on:
      - mongo
