/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as mainLayoutRouteImport } from './main-layout'
import { Route as homeHomePageRouteRouteImport } from './home/HomePage/route'
import { Route as djLayoutRouteImport } from './dj/layout'
import { Route as playPlayPageRouteRouteImport } from './play/PlayPage/route'
import { Route as djDJConsolePageRouteRouteImport } from './dj/DJConsolePage/route'
import { Route as djCollectionPageRouteRouteImport } from './dj/CollectionPage/route'

const mainLayoutRoute = mainLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const homeHomePageRouteRoute = homeHomePageRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainLayoutRoute,
} as any)
const djLayoutRoute = djLayoutRouteImport.update({
  id: '/dj/_dj-layout',
  path: '/dj',
  getParentRoute: () => mainLayoutRoute,
} as any)
const playPlayPageRouteRoute = playPlayPageRouteRouteImport.update({
  id: '/play/$station',
  path: '/play/$station',
  getParentRoute: () => mainLayoutRoute,
} as any)
const djDJConsolePageRouteRoute = djDJConsolePageRouteRouteImport.update({
  id: '/$station/',
  path: '/$station/',
  getParentRoute: () => djLayoutRoute,
} as any)
const djCollectionPageRouteRoute = djCollectionPageRouteRouteImport.update({
  id: '/$station/collection/$collectionId',
  path: '/$station/collection/$collectionId',
  getParentRoute: () => djLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeHomePageRouteRoute
  '/play/$station': typeof playPlayPageRouteRoute
  '/dj': typeof djLayoutRouteWithChildren
  '/dj/$station': typeof djDJConsolePageRouteRoute
  '/dj/$station/collection/$collectionId': typeof djCollectionPageRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof homeHomePageRouteRoute
  '/play/$station': typeof playPlayPageRouteRoute
  '/dj': typeof djLayoutRouteWithChildren
  '/dj/$station': typeof djDJConsolePageRouteRoute
  '/dj/$station/collection/$collectionId': typeof djCollectionPageRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof mainLayoutRouteWithChildren
  '/_layout/': typeof homeHomePageRouteRoute
  '/_layout/play/$station': typeof playPlayPageRouteRoute
  '/_layout/dj/_dj-layout': typeof djLayoutRouteWithChildren
  '/_layout/dj/_dj-layout/$station/': typeof djDJConsolePageRouteRoute
  '/_layout/dj/_dj-layout/$station/collection/$collectionId': typeof djCollectionPageRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play/$station'
    | '/dj'
    | '/dj/$station'
    | '/dj/$station/collection/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/play/$station'
    | '/dj'
    | '/dj/$station'
    | '/dj/$station/collection/$collectionId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/play/$station'
    | '/_layout/dj/_dj-layout'
    | '/_layout/dj/_dj-layout/$station/'
    | '/_layout/dj/_dj-layout/$station/collection/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeHomePageRouteRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/_layout/dj/_dj-layout': {
      id: '/_layout/dj/_dj-layout'
      path: '/dj'
      fullPath: '/dj'
      preLoaderRoute: typeof djLayoutRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/_layout/play/$station': {
      id: '/_layout/play/$station'
      path: '/play/$station'
      fullPath: '/play/$station'
      preLoaderRoute: typeof playPlayPageRouteRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/_layout/dj/_dj-layout/$station/': {
      id: '/_layout/dj/_dj-layout/$station/'
      path: '/$station'
      fullPath: '/dj/$station'
      preLoaderRoute: typeof djDJConsolePageRouteRouteImport
      parentRoute: typeof djLayoutRoute
    }
    '/_layout/dj/_dj-layout/$station/collection/$collectionId': {
      id: '/_layout/dj/_dj-layout/$station/collection/$collectionId'
      path: '/$station/collection/$collectionId'
      fullPath: '/dj/$station/collection/$collectionId'
      preLoaderRoute: typeof djCollectionPageRouteRouteImport
      parentRoute: typeof djLayoutRoute
    }
  }
}

interface djLayoutRouteChildren {
  djDJConsolePageRouteRoute: typeof djDJConsolePageRouteRoute
  djCollectionPageRouteRoute: typeof djCollectionPageRouteRoute
}

const djLayoutRouteChildren: djLayoutRouteChildren = {
  djDJConsolePageRouteRoute: djDJConsolePageRouteRoute,
  djCollectionPageRouteRoute: djCollectionPageRouteRoute,
}

const djLayoutRouteWithChildren = djLayoutRoute._addFileChildren(
  djLayoutRouteChildren,
)

interface mainLayoutRouteChildren {
  homeHomePageRouteRoute: typeof homeHomePageRouteRoute
  playPlayPageRouteRoute: typeof playPlayPageRouteRoute
  djLayoutRoute: typeof djLayoutRouteWithChildren
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  homeHomePageRouteRoute: homeHomePageRouteRoute,
  playPlayPageRouteRoute: playPlayPageRouteRoute,
  djLayoutRoute: djLayoutRouteWithChildren,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainLayoutRoute: mainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
