name: CI
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 18
        node_arch:
          - x64
        arch:
          - x64

        include:
          - os: ubuntu-latest
            build-arch: linux-x64

          # - os: windows-latest
          #   build-arch: win32-x64

          # - os: macos-11
          #   build-arch: darwin-x64+arm64

    name: Build ${{ matrix.build-arch }}
    runs-on: ${{ matrix.os }}
    env:
      BUILD_ARCH: ${{ matrix.build-arch }}
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_arch }}

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Dependencies (Linux)
        if: contains(matrix.build-arch, 'linux')
        run: |
          sudo apt install g++ make pkg-config libtag1-dev libsamplerate0-dev libfreetype6-dev libcurl4-openssl-dev libasound2-dev libx11-dev libxrandr-dev

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build native
        working-directory: ./packages/node-medley
        run: |
          pnpm install --no-frozen-lockfile --ignore-scripts
          pnpm run prebuild-$BUILD_ARCH

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build-arch }}
          path: ./packages/node-medley/prebuilds


