name: node-medley native module
on:
  push:
    paths:
      - .github/workflows/node-medley.yml
      - packages/node-medley/src/**
      - packages/node-medley/scripts/**
      - packages/node-medley/binding.gyp
      - packages/node-medley/package.json
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node_version: 18
            node_arch: x64
            build-arch: linux-x64

          # - os: windows-latest
          #   node_version: 18
          #   node_arch: x64
          #   build-arch: win32-x64

          # Github Actions only supports x86_64 arch for now.
          - os: macos-12
            node_version: 18
            node_arch: x64
            build-arch: darwin-x64

    name: Build ${{ matrix.build-arch }}
    runs-on: ${{ matrix.os }}
    env:
      BUILD_ARCH: ${{ matrix.build-arch }}
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_arch }}

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Dependencies (Linux)
        if: contains(matrix.build-arch, 'linux')
        run: |
          sudo apt install g++ make pkg-config libtag1-dev libsamplerate0-dev libfreetype6-dev libcurl4-openssl-dev libasound2-dev libx11-dev libxrandr-dev

      - name: Dependencies (macOS)
        if: contains(matrix.build-arch, 'darwin')
        run: |
          brew install --build-from-source taglib
          brew install libsamplerate

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare
        working-directory: ./packages/node-medley
        run: |
          pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Build native
        working-directory: ./packages/node-medley
        run: |
          pnpm run prebuild-$BUILD_ARCH

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build-arch }}
          path: ./packages/node-medley/prebuilds


